[project]
name = "dlp-init"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "markitdown>=0.0.1a5",
    "python-magic>=0.4.27",
    "python-magic-bin>=0.4.14",
    "pyyaml>=6.0.2",
]
