threshold: 0.75
security_marks:
  - 机密
  - 秘密
  - 严禁
  - 禁止
  - 极大
  - 重大

sensitive_patterns:
  人事管理:
    keywords:
      - 任命书
      - 聘书
      - 政治面貌
      # - 所有员工
      - 讨论会
      - 应聘人员
      - 人员分布
      # - 招聘
      # - 负责人
      - 离职原因
      # - 督导
      - 许可审批
      - 人事档案
      - 工作交接
      # - 员工编号
      - 离职申请
      - 绩效考核
      - 体检表
      - 简历
      - 考勤加班
      # - 管理制度
      # - 求职意向
      # - 工作经历
      # - 人力资源
      - 组织架构
      - 通讯录
      - 制药
      # - 高新技术
      - 经济效益
      - 年产量
      - 事业单位
      - 年度报告
      - 经费
      - 销售利润
      - 应收款
      - 发文
      - 成绩统计
      - 合格率
      - 工程项目
      - 工程造价
      - 所属部门
      # - 文号
      # - 凭证
      - 预约记录
    weight: 0.95
  财务核心:
    keywords:
      - 固定资产
      - 折旧明细
      - 审计机关
      - 内部收益率
      - 资产清单
      - 投资方案
      - 投资情况
      - 投资业绩
      - 处置记录
      - 业务管理
      - 业务统计
      - 月折旧额
      - 贷方合计
      - 借方合计
      - 凭证编号
      - 凭证号
      - 记账凭证
      - 应付账款
      - 应收账款
      - 贷款本金
      - 还款计划
      - 银行账户
      - 成本核算
      # - 费用预算
      - 月度预算
      - 对照表
      - 验收表
      - 统计表
      - 科目表
      - 互评表
      - 收支明细
      - 票据号码
      - 兹证明
      - 信函
      - 费用结算
      - 支出证明
      - 报销单
      - 审计报告
      # - 利润表
      - 调查表
      - 资金周转
      - 筹资
      - 现金流量
      - 纳税申报
      - 纳税人
      - 国税
      - 合同编号
      - 申请单
      - 申请表
      - 税费率
      - 个税金
      - 应交所得税
      - 成本利润率
      - 利润统计
      - 费用计算
      # - 资产负债表
      - 财务分析
      - 财务管理
      - 管理系统
      - 情况分析
      - 财务指标
      - 财务费
      - 财务部
      - 丁字帐
      - 培训报告
      - 台账
      - 资产原值
      - 股票记账
      - 股票账户
      - 股票交易记录
      - 业绩提成
      - 营业额
      - 提成比例
      - 提成计算
      - 财政部
      - 财政预算
      - 财政支
      - 财政拨款
      - 财务报表
      - 现金流量表
      - 财务预算
      - 风险管理
      - 风险控制
      - 资本结构
      - 比率分析
      - 财务透明度
      - 财务合规
      - 财务决策
      - 财务舞弊
      - 会计政策
      - 会计账簿
      - 支票
      - 会计凭证
      - 参保人
      - 会计信息系统
      - 会计档案
      - 会计舞弊
      - 会计审计
      - 审计工作
      - 工作流程
      - 会计内部控制
      - 会计电算化
      - 会计结算
      - 费用结算
      - 会计报告
      - 清算资产
      - 会计报表
      - 会计监督
      - 内部审计
      - 审计底稿
      - 审计计划
      - 审计质量控制
      - 审计披露
      - 审计调整
      - 审计信息系统
      - 税务内部控制
      - 损益表
      - 清偿表
      - 资金流动性
      # - 调度
      - 集中管理
      # - 结算
      - 融通
      - 周转率
      - 使用效率
      - 对账明细
      - 明细表
      - 對帳明細
      - 财务系统集成
      - 财务数据挖掘
      - 拟引资
    weight: 0.9
  商业机密:
    keywords:
      - 竞品分析
      - 市场策略
      - 产品规划
      - 国企
      - 定价策略
      - 战略规划
      - 质量监测
      - 营销方案
      - 存档人
      - 档案登记
      - 竞争对手分析
      - 竞品销售费用
      - 市场份额
      - 产品组合策略
      - 客户画像
      - 渠道成本
      - 客户清单
      - 代理协议
      - 销售政策
      - 销售情况
      - 客户代码
      - 销售机密
      - 销售分析
      - 总额统计
      - 数据分析
      - 市场占有率
      - 生产工序
      - 生产报表
      - 制表人
      - 制表单位
      - 销售业绩
      - 业绩表
      # - 周报表
      # - 月报表
      # - 年报表
      # - 季报表
      - 工艺流程
      - 研发路线
      - 技术方案
      - 经济技术
      - 配方参数
      # - 质量标准
      - 供应商名录
      - 采购策略
      - 库存管理
      - 物流方案
    weight: 0.95
  法律合规:
    keywords:
      - 合同编号
      - 编制单位
      # - 经办人
      - 复核人
      - 债权债务
      - 制表人
      - 保密协议
      - 竞业限制
      - 企业名称
      - 知识产权
      - 借款合同
      - 短期借款
      - 公司章程
      - 财务审计报告
      - 法律意见书
      - 诉讼文件
      - 仲裁协议
    weight: 0.9
  股票与业绩:
    keywords:
      - 股票期权
      - 工商登记
      - 股权转让
      - 股权激励
      - 应收股利
      - 应收票据
      - 业绩提成
      - 提成比例
      - 提成计算
      - 股票分红
      - 股票授予
      - 股票回购
      - 股票业绩
      # - 股票收益
      - 股票分配
      - 股票协议
      - 股票奖励
      - 股票转让
      - 股票交易
      - 公章
      - 股票市场
      - 股票价格
      - 股票代码
      - 股票账户
      - 资金账户
      - 股票记账
      - 股票交易记录
      - 重点建设
      - 营业额
      - 竞争对手
      - 详细信息
      - 发展策略
      # - 合作伙伴
    weight: 0.95
  风险行为:
    keywords:
      - 信用卡
      - 赌博
      - 毒品
      - 套现
      - 高利贷
    weight: 0.98
  个人信息:
    keywords:
      - 账号
      - ID CARD
    weight: 0.98

structured_patterns:
  "实发工资[\\s：:]+[0-9]+元": 0.95
  "金额[\\s：:]+[0-9]+元": 0.95
  
regex_patterns:
  信用卡号码: 
    pattern: "\\b\\d{16}\\b"
    weight: 0.95
  社会安全号: 
    pattern: "\\b\\d{3}-\\d{2}-\\d{4}\\b"
    weight: 0.95
  工资金额:
    pattern: "工资[\\s：:]*\\d+([.,]\\d+)?[元¥]"
    weight: 0.95
  密码模式:
    pattern: "密码[\\s：:]*\\w{6,20}"
    weight: 0.98
