threshold: 0.75
security_marks:
  - 机密
  - 秘密
  - 内部
  - 保密
  - 严禁
  - 禁止
  - 不得
sensitive_patterns:
  人事管理:
    keywords:
      - 任命书
      - 聘书
      - 人才培养
      - 所有员工
      - 讨论会
      - 应聘人员
      - 招聘
      - 人事档案
      - 员工编号
      - 离职申请
      - 绩效考核
      - 考核指标
      - 简历
      - 管理制度
      - 求职意向
      - 工作经历
      - 教育背景
      - 人力资源
      - 组织架构
    weight: 0.95
  财务核心:
    keywords:
      - 固定资产
      - 折旧明细
      - 内部收益率
      - 资产清单
      - 投资方案
      - 处置记录
      - 月折旧额
      - 申请经费
      - 年产量
      - 经济效益
      - 应付账款
      - 应收账款
      - 贷款本金
      - 还款计划
      - 银行账户
      - 成本核算表
      - 费用预算
      - 支出证明
      - 报销单
      - 审计报告
      - 销售额
      - 利润表
      - 资金周转
      - 现金流量
      - 纳税申报
      - 进项税额
      - 填报单位
      - 制表单位
      - 增值税申报
      - 成本利润率
      - 资产负债表
      - 财务分析报告
      - 资产原值
      - 股票记账
      - 股票账户
      - 股票交易记录
      - 业绩提成
      - 营业额
      - 提成比例
      - 提成计算
      - 财政
      - 应收款项
      - 财务报表
      - 销售利润
      - 现金流量表
      - 财务预算
      - 财务风险管理
      - 资本结构
      - 比率分析
      - 财务透明度
      - 财务合规
      - 财务决策
      - 财务舞弊
      - 会计政策
      - 会计账簿
      - 会计凭证
      - 会计信息系统
      - 会计档案
      - 会计舞弊
      - 会计审计
      - 会计内部控制
      - 会计电算化
      - 会计结算
      - 会计报告
      - 会计监督
      - 内部审计
      - 审计底稿
      - 审计计划
      - 审计质量控制
      - 审计披露
      - 审计调整
      - 审计信息系统
      - 税务内部控制
      - 资金流动性
      - 预算
      - 调度
      - 集中管理
      - 风险
      - 成本
      - 结算
      - 融通
      - 周转率
      - 使用效率
      - 会议记录
      - 安全
      - 预约记录
      - 对账
      - 凭证
      - 文号
      - 发文
      - 财务系统集成
      - 财务数据挖掘
    weight: 0.9
  商业机密:
    keywords:
      - 竞品分析
      - 市场策略
      - KPI
      - 产品规划
      - 定价策略
      - 战略规划
      - 营销方案
      - 竞争对手分析
      - 高新技术
      - 制药
      - 竞品销售费用
      - 市场份额
      - 产品组合策略
      - 客户画像
      - 渠道成本
      - 验收表
      - 客户清单
      - 代理协议
      - 销售政策
      - 客户代码
      - 销售机密
      - 销售业绩
      - 业绩表
      - 工艺流程
      - 研发路线
      - 技术方案
      - 配方参数
      - 质量标准
      - 供应商名录
      - 采购策略
      - 库存管理
      - 物流方案
    weight: 0.95
  法律合规:
    keywords:
      - 合同编号
      - 编制
      - 经办人
      - 复核
      - 债权债务
      - 保密协议
      - 竞业限制
      - 知识产权
      - 借款合同
      - 公司章程
      - 财务审计报告
      - 法律意见书
      - 股权转让
      - 诉讼文件
      - 仲裁协议
    weight: 0.9
  股票与业绩:
    keywords:
      - 股票期权
      - 股权激励
      - 业绩提成
      - 提成比例
      - 提成计算
      - 股票分红
      - 股票授予
      - 股票回购
      - 股票业绩
      - 股票收益
      - 股票分配
      - 股票协议
      - 股票奖励
      - 股票转让
      - 股票交易
      - 股票市场
      - 股票价格
      - 股票代码
      - 股票账户
      - 股票记账
      - 股票交易记录
      - 营业额
      - 竞争对手
      - 合作伙伴
    weight: 0.95
structured_patterns:
  "实发工资[\\s：:]+[0-9]+元": 0.95
  "金额[\\s：:]+[0-9]+元": 0.95
# number_patterns:
